### ISSUE TITLE
Error in QA system on x86 Ubunt, OpenJDK

### ISSUE THREAD

**Issue by Timopheym** [jhauswald/sirius#73]
``` +++++ Analyzing question (2015-05-19 22:32:18) +++++
Normalization: what be the speed of light

Answer types:
NErate->NEspeed

Interpretations:
Property: SPEED
Target: light

Predicates:
-

+++++ Generating queries (2015-05-19 22:32:30) +++++
Query strings:
speed light
("speed of light" OR "light speed")
"light" speed light
"the speed of light is"
"is the speed of light"

+++++ Searching (2015-05-19 22:32:30) +++++
OpenJDK Server VM warning: You have loaded library /home/timopheym/dev/sirius/sirius-application/question-answer/lib/search/libindri_jni.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "Thread-19" Exception in thread "Thread-18" Exception in thread "Thread-22" Exception in thread "Thread-21" Exception in thread "Thread-20" java.lang.UnsatisfiedLinkError: /home/timopheym/dev/sirius/sirius-application/question-answer/lib/search/libindri_jni.so: /home/timopheym/dev/sirius/sirius-application/question-answer/lib/search/libindri_jni.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at lemurproject.indri.indriJNI.<clinit>(indriJNI.java:109)
	at lemurproject.indri.QueryEnvironment.<init>(QueryEnvironment.java:39)
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NoClassDefFoundError: Could not initialize class lemurproject.indri.indriJNI
	at lemurproject.indri.QueryEnvironment.<init>(QueryEnvironment.java:39)
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NoClassDefFoundError: Could not initialize class lemurproject.indri.indriJNI
	at lemurproject.indri.QueryEnvironment.<init>(QueryEnvironment.java:39)
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NoClassDefFoundError: Could not initialize class lemurproject.indri.indriJNI
	at lemurproject.indri.QueryEnvironment.<init>(QueryEnvironment.java:39)
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NoClassDefFoundError: Could not initialize class lemurproject.indri.indriJNI
	at lemurproject.indri.QueryEnvironment.<init>(QueryEnvironment.java:39)
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
```
uname -a
```
Linux timopheym-System-Product-Name 3.16.0-37-generic #51~14.04.1-Ubuntu SMP Wed May 6 15:24:07 UTC 2015 i686 i686 i686 GNU/Linux

```
 java -version
```java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK Client VM (build 24.79-b02, mixed mode, sharing)```

What should i change (do), should i have x64 machine? can you provide x86 libraries?

**Comment by Timopheym** [comment]
Duplicate of #62
